export const SORT_RECENTLY_ADDED = "SORT_RECENTLY_ADDED";
export const SORT_RELEASE_DATE = "SORT_RELEASE_DATE";
export const SORT_RATING = "SORT_RATING";
export const SORT_ALPHABETICALLY = "SORT_ALPHABETICALLY";
